### ISSUE TITLE
Allow hook to wp_footer()

### ISSUE THREAD

**Issue by odie2** [projectestac/wordpress-add-to-any#1]
Hi,

I just done rewriting [Hyphenator](https://wordpress.org/plugins/hyphenator/) plugin (version 5.1.5 not yet published) in favor of cleaning blocking-loading scripts in head of my websites.

As I am using AddToAny on most of my websites it would be nice to have possibility to hook it to `wp_footer()` instead of `wp_head()`.

I could do it, but you have also _unclean_ code and some instances of `<script>`, so I prefer to don't touch this. However, if you were so helpful to do it, below are some advices I used in Hyphenator:

`add_option( 'hyphenator_scripthook', 'wp_head' );`
`add_action( get_option( 'hyphenator_scripthook' ), 'hyphenator_hook', 100 );`

```
<select id="opt10" name="hyphenator_scripthook">
    <option value="wp_head" <?php selected( $hyphenator_['scripthook'], 'wp_head' ); ?>>wp_head()</option>
    <option value="wp_footer" <?php selected( $hyphenator_['scripthook'], 'wp_footer' ); ?>>wp_footer()</option>
</select>
```

Thanks in advance,
Greetings

**Comment by toniginard** [comment]
```
 Hi!
```

This is not the official repository of the plugin Add To Any. This repository is for our customization of the plugin. If you want to contact the developers, I suggest to use the plugin forum or submit a ticket in the TRAC: https://wordpress.org/plugins/add-to-any/developers/

We are not developing this plugin, so we cannot help you.

Best wishes,

**Comment by odie2** [comment]
Yea, I didn't readed description on the top, just have clicked first matching link in search engine ;)
Thanks for figuring me out.

Reported on [forum](https://wordpress.org/support/topic/allow-hook-to-wp_footer).

Greetings
