### ISSUE TITLE
remove or disable tracking to respect privacy and be GDPR compliant

### ISSUE THREAD

**Issue by rebelcode-xr** [projectestac/wordpress-add-to-any#18]
Hello and thanks for this plugin!

I love it but I've encountered a privacy issue: there's a JS **on by default and without option to disable it** tracking users and violating the GDPR.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/63522951/157097853-e8ab8925-950e-4034-8883-190c190ba280.png">

This is the tool I used to discover it:
https://www.violating-gdpr.com/

This is the tracker url:
https://static.addtoany.com/menu/page.js

I would love to continue using the plugin but only without the JS tracker, otherwise I will (sadly) remove it and discourage its use.

**SOLUTION**
I propose to add an option to enable it (opt-in after installation), so the WP admin is aware of the choice.
In case of tracking enabled the users should also be notified.

Thank you! 🙏

**Comment by toniginard** [comment]
Hi,

This is not the official repository of the add-to-any plugin. This is just a fork where we maintain a customized version for our needs. So, please, report this issue to the official forum, where the developers and maintainers can see it:

https://wordpress.org/support/plugin/add-to-any/


Best wishes,

**Comment by rebelcode-xr** [comment]
Oh damn 🤦  I'm sorry! 🙏 

I found a solution (opt-out) in the meantime:
https://www.addtoany.com/buttons/customize/wordpress/host_cache
